name: sentiment-analysis

services:
  triton-server:
    image: nvcr.io/nvidia/tritonserver:24.05-py3
    container_name: triton-server
    restart: unless-stopped
    ports:
      - "8000:8000"  # HTTP
      - "8001:8001"  # GRPC
      - "8002:8002"  # Metrics
    volumes:
      - ./triton-model-repository:/models
      - /tmp/triton-cache:/tmp/triton-cache
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      tritonserver --model-repository=/models
      --allow-gpu-metrics=true
      --allow-cpu-metrics=true
      --log-verbose=1
      --strict-model-config=false
      --exit-on-error=false
      --backend-config=tensorrt,enable-nvtx=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v2/health/ready"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - sentiment-net

  fastapi-service:
    build:
      context: ./fastapi-service
      dockerfile: Dockerfile
    container_name: sentiment-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TRITON_SERVER_URL=triton-server:8001
      - MODEL_NAME=sentiment_analysis_tensorrt
      - MAX_BATCH_SIZE=4
      - LOG_LEVEL=INFO
    depends_on:
      triton-server:
        condition: service_healthy
    volumes:
      - ./triton-model-repository:/app/triton-model-repository:ro
      - ./logs:/app/logs
      - ~/.cache/huggingface:/root/.cache/huggingface
    networks:
      - sentiment-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

networks:
  sentiment-net:
    driver: bridge 